=== Red5d/memejson/meme-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "background_uri": {
        "type": "string",
        "format": "uri"
      },
      "top_text": {
        "type": "string"
      },
      "bottom_text": {
        "type": "string"
      },
      "free_text": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "position": {
              "type": "object",
              "properties": {
                "x": {
                  "type": "number"
                },
                "y": {
                  "type": "number"
                }
              }
            }
          }
        }
      },
      "formatting": {
        "type": "object",
        "properties": {
          "font": {
            "type": "string"
          },
          "font_color": {
            "type": "string"
          },
          "font_size": {
            "type": "integer"
          },
          "top_padding": {
            "type": "integer"
          },
          "bottom_padding": {
            "type": "integer"
          },
          "left_padding": {
            "type": "integer"
          },
          "right_padding": {
            "type": "integer"
          }
        }
      }
    },
    "required": ["background_uri", "top_text", "bottom_text"]
  }

=== Red5d/memejson/example.json
{
    "background_uri": "https://i.imgflip.com/q2w0.jpg",
    "top_text": "Hello",
    "bottom_text": "World!",
    "free_text": [
      {
        "text": "Lorem ipsum",
        "position": {
          "x": 10,
          "y": 20
        }
      },
      {
        "text": "dolor sit amet",
        "position": {
          "x": 30,
          "y": 40
        }
      }
    ],
    "formatting": {
      "font": "Arial",
      "font_color": "#000000",
      "top_padding": 5,
      "bottom_padding": 5,
      "left_padding": 10,
      "right_padding": 10
    }
  }
